language: cpp
# Use the faster container-based infrastructure.
#sudo: false
# https://github.com/travis-ci/travis-ci/issues/9033
sudo: true
env:
  global:

# -m32 is not supported 
# no poppler, openjpeg, uuid, json
# no swig
matrix:
  fast_finish: true
  include:
    - compiler: gcc
      os: linux
      env:
        - CXXFLAGS="-g -O0 -Wall -Wextra -m64 -W -Wshadow -Wunused-variable -Wunused-parameter -Wunused-function -Wunused -Wno-system-headers -Wno-deprecated -Woverloaded-virtual -Wwrite-strings -fprofile-arcs -ftest-coverage"
        - CFLAGS="-g -O0 -Wall -Wextra -m64 -W -Wshadow -Wunused-variable -Wunused-parameter -Wunused-function -Wunused -Wno-system-headers -Wno-deprecated -Wwrite-strings -fprofile-arcs -ftest-coverage"
        - LDFLAGS="-fprofile-arcs -ftest-coverage"
        - CMAKE_EXTRA="-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=ON -DUSE_FSL_CODE:BOOL=ON -DUSE_CIFTI_CODE:BOOL=ON -DUSE_NIFTI2_CODE:BOOL=ON"
        - B_NAME=system_gcc
        - COVERAGE="YES"
    - compiler: clang
      os: linux
      env:
        - ASAN_OPTIONS=verbosity=1:log_threads=1
        - CFLAGS="-Wall -Wextra -m64 -W -Wshadow -Wunused-variable -Wunused-parameter -Wunused-function -Wunused -Wno-system-headers -Wno-deprecated -Wwrite-strings -fsanitize=address,undefined"
        - CXXFLAGS="-g -Wall -Wextra -m64 -fsanitize=address,undefined"
        - CMAKE_EXTRA="-DUSE_FSL_CODE:BOOL=ON -DUSE_CIFTI_CODE:BOOL=ON -DUSE_NIFTI2_CODE:BOOL=ON"
        - B_NAME=fsanitize
        - COVERAGE="NO"
    - compiler: clang
      os: osx
      env:
        - CFLAGS="-O3 -Wall -Wextra -Wshadow -Wunused-variable -Wunused-parameter -Wunused-function -Wunused -Wno-system-headers -Wno-deprecated -Wwrite-strings " # -m64 -fsanitize=address,undefined
        - CXXFLAGS="-O3 -Wall -Wextra -Wshadow -Wunused-variable -Wunused-parameter -Wunused-function -Wunused -Wno-system-headers -Wno-deprecated -Wwrite-strings " # -m64 -fsanitize=address,undefined
        - CMAKE_EXTRA="-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=ON -DUSE_FSL_CODE:BOOL=ON -DUSE_CIFTI_CODE:BOOL=ON -DUSE_NIFTI2_CODE:BOOL=ON"
        - B_NAME=osx_clang
        - COVERAGE="NO"

before_install:
  #- env
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      mkdir -p ${TRAVIS_BUILD_DIR}/deps
      pushd ${TRAVIS_BUILD_DIR}/deps
        #CMAKE_URL="https://cmake.org/files/v3.13/cmake-3.13.2-Linux-x86_64.tar.gz"
        CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.13.2/cmake-3.13.2-Linux-x86_64.tar.gz"
        mkdir -p cmake-3.13.2 && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake-3.13.2
        export PATH=${TRAVIS_BUILD_DIR}/deps/cmake-3.13.2/bin:${PATH}
      popd
    else
      brew install cmake || brew upgrade cmake
    fi
  - cd ${TRAVIS_BUILD_DIR}
  - cmake --version
install: true
before_script: true
script:
  - cmake -Wno-dev -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=None -DBUILD_TESTING:BOOL=ON -DNIFTI_BUILD_APPLICATIONS:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILDNAME:STRING=${TRAVIS_OS_NAME}-${TRAVIS_BRANCH}-${B_NAME} ${CMAKE_EXTRA} .
  - ctest -D ExperimentalStart
  - ctest -D ExperimentalBuild -j2
  - ctest -D ExperimentalTest -j2 || true
  - if [[ "${COVERAGE}" == "YES" ]] ; then ctest -D ExperimentalCoverage || true ; fi
  - ctest -D ExperimentalSubmit || true

after_success: true
after_failure: true
after_script: true