language: cpp
# Use the faster container-based infrastructure.
#sudo: false
# https://github.com/travis-ci/travis-ci/issues/9033
sudo: true
env:
  global:

# -m32 is not supported 
# no poppler, openjpeg, uuid, json
# no swig
matrix:
  fast_finish: true
  include:
    - compiler: gcc
      os: linux
      env:
        - CFLAGS="-Wall -Wextra -m64"
        - CXXFLAGS="-Wall -Wextra -m64"
        - CMAKE_EXTRA="-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=ON -DGDCM_USE_SYSTEM_OPENSSL:BOOL=ON -DGDCM_WRAP_PYTHON:BOOL=OFF -DGDCM_WRAP_CSHARP:BOOL=OFF -DGDCM_WRAP_JAVA:BOOL=OFF -DGDCM_WRAP_PHP:BOOL=OFF -DGDCM_USE_SYSTEM_EXPAT:BOOL=ON -DGDCM_USE_SYSTEM_JSON:BOOL=OFF -DGDCM_USE_SYSTEM_LIBXML2:BOOL=ON -DGDCM_USE_SYSTEM_OPENJPEG:BOOL=OFF -DGDCM_USE_SYSTEM_POPPLER:BOOL=OFF -DGDCM_USE_SYSTEM_UUID:BOOL=OFF -DGDCM_USE_SYSTEM_ZLIB:BOOL=ON -DGDCM_BUILD_DOCBOOK_MANPAGES:BOOL=OFF"
        - B_NAME=system
    - compiler: clang
      os: linux
      env:
        - ASAN_OPTIONS=verbosity=1:log_threads=1
        - CFLAGS="-Wall -Wextra -m64 -fsanitize=address,undefined"
        - CXXFLAGS="-g -Wall -Wextra -m64 -fsanitize=address,undefined"
        - CMAKE_EXTRA="-DGDCM_BUILD_DOCBOOK_MANPAGES:BOOL=OFF"
        - B_NAME=fsanitize
    - compiler: clang
      os: osx
      env:
        - CFLAGS="-Wall -Wextra" # -m64 -fsanitize=address,undefined
        - CXXFLAGS="-Wall -Wextra" # -m64 -fsanitize=address,undefined
        - CMAKE_EXTRA="-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=ON -DGDCM_BUILD_DOCBOOK_MANPAGES:BOOL=OFF"
        - B_NAME=fsanitize

before_install:
  #- env
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      mkdir -p ${TRAVIS_BUILD_DIR}/deps
      pushd ${TRAVIS_BUILD_DIR}/deps
        CMAKE_URL="https://cmake.org/files/v3.13/cmake-3.13.1-Linux-x86_64.tar.gz"
        mkdir -p cmake-3.13.1 && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake-3.13.1
        export PATH=${TRAVIS_BUILD_DIR}/deps/cmake-3.13.1/bin:${PATH}
      popd
    else
      brew install cmake || brew upgrade cmake
    fi
  - cd ${TRAVIS_BUILD_DIR}
  - cmake --version
install: true
before_script: true
script:
  - cmake -Wno-dev -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=None -DGDCM_BUILD_TESTING:BOOL=ON -DGDCM_BUILD_APPLICATIONS:BOOL=ON -DGDCM_BUILD_SHARED_LIBS:BOOL=ON -DGDCM_ALLOW_INSOURCE_BUILD:BOOL=ON -DBUILDNAME:STRING=${TRAVIS_OS_NAME}-${TRAVIS_BRANCH}-${B_NAME} ${CMAKE_EXTRA} .
  - ctest -D ExperimentalStart
  - ctest -D ExperimentalBuild -j2
  - ctest -D ExperimentalTest -j2 || true
  - ctest -D ExperimentalSubmit || true

after_success: true
after_failure: true
after_script: true
